CODE Consignação: ~ # Java, ignorar
CODE Salve Vidas: sihro
CODE Alpha: alpha-solicitacoes-carta-de-servico-web
CODE PPE: processo-seletivo
CODE Processos Seletivos: processo-seletivo

CODE Procon: portal-do-governo
CODE Portal Rondônia: portal-do-governo
CODE Portal Rondônia TemTudo: rondonia-tem-turismo
CODE Rondonia: portal-do-governo

CODE Assine aqui: canetada # você confirmou que “Assine Aqui” = Canetada

# Confirmados agora:
CODE SID: sid-web
CODE Drive.sistemas: gov-drive

# Aguardando confirmação ou realmente sem aplicação mapeada:
CODE Eventos: ~
CODE CaveirasJobs: ~
CODE Organograma: ~ # Node / Ignorar
CODE Wekan: ~ # Não é da sua secretaria
CODE DataLeitos: ~
CODE Matomo: ~
CODE Meu Acesso: ~
CODE Documentos.sistemas: ~
CODE Central DEV: ~
CODE Reserva de Vaga Online: ~
CODE Geração Emprego: ~
